version: 2
updates:
  # Mocked projects for dependency notifications
  - package-ecosystem: "nuget"
    directory: "/tracer/dependabot"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:dependabot"
    ignore:
      - dependency-name: "MessagePack" # Locked at a version that supports our net452 build target
      - dependency-name: "*" # Ignore patches for all integrations
        update-types: ["version-update:semver-patch"]
